### ISSUE TITLE
Upgrade our version of PEGjs

### ISSUE THREAD

**Issue by savetheclocktower** [pulsar-edit/snippets#14]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

The version of PEGjs we're on (v0.8.0) makes use of `eval`, which means we have to use the [loophole](https://github.com/pulsar-edit/loophole) package to monkeypatch those `eval` calls.

Instead, we could probably just upgrade to PEGjs v0.10.0, which seems to have removed all the `eval`s in favor of a `vm.runInContext`-type approach that is the basis of loophole in the first place.

### What benefits does this feature provide?

We can update one dependency to a newer version and remove another dependency altogether.

### Any alternatives?

The status quo is one alternative. Another is to keep the version we're on, but move `pegjs` and `loophole` into `devDependencies` and force a developer to recompile the `.pegjs` file whenever it's changed via some sort of NPM script. Harder to iterate when you're hacking on it, but more secure.

But probably best to just upgrade the package.

**Comment by confused-Techie** [comment]
Resolved by #15
